import os
import re
from pathlib import Path
from datetime import datetime


PROJECT_ROOT = Path(r"C:\Users\55124152\OneDrive - MMU\DLS\OER_Rebirth")
AGENTS_DIR = PROJECT_ROOT / ".continue" / "agents"
TEMPLATES_DIR = PROJECT_ROOT / "templates"
STATIC_DIR = PROJECT_ROOT / "static"
RESOURCES_DIR = PROJECT_ROOT / "resources"
OER_REBIRTH_DIR = PROJECT_ROOT / "oer_rebirth"

AGENTS_DIR.mkdir(parents=True, exist_ok=True)


def read_lines(path: Path) -> list[str]:
    if not path.is_file():
        return []
    try:
        return path.read_text(encoding="utf-8", errors="ignore").splitlines()
    except Exception:
        return []


def write_md(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def build_project_overview() -> None:
    ts = datetime.now().isoformat(timespec="seconds")
    lines: list[str] = []
    lines.append("# Project Overview")
    lines.append("")
    lines.append(f"_Auto-generated by refresh_project_maps.py at {ts}_")
    lines.append("")
    lines.append("## Paths")
    lines.append(f"- **Project root**: `{PROJECT_ROOT}`")
    lines.append(f"- **Django config**: `{OER_REBIRTH_DIR / 'settings.py'}`")
    lines.append(f"- **Main app (resources)**: `{RESOURCES_DIR}`")
    lines.append(f"- **Templates**: `{TEMPLATES_DIR}`")
    lines.append(f"- **Static**: `{STATIC_DIR}`")
    lines.append(f"- **Scripts**: `{PROJECT_ROOT / 'scripts'}`")
    lines.append("")
    lines.append("## Notes")
    lines.append("- This file is a high-level entry point for agents and humans.")
    lines.append("- See other `*_map.md` files in `.continue/agents` for more detail.")
    lines.append("")
    write_md(AGENTS_DIR / "project_overview.md", "\n".join(lines))


def build_project_structure() -> None:
    ts = datetime.now().isoformat(timespec="seconds")
    structure_txt = AGENTS_DIR / "project_structure.txt"

    if not structure_txt.is_file():
        project_structure: list[str] = []
        for root, dirs, files in os.walk(PROJECT_ROOT):
            rel_root = Path(root).relative_to(PROJECT_ROOT)
            if "venv" in rel_root.parts or "__pycache__" in rel_root.parts:
                continue
            for name in files:
                rel_path = str((Path(root) / name).relative_to(PROJECT_ROOT))
                project_structure.append(rel_path)
        structure_txt.write_text(
            "\n".join(sorted(project_structure)), encoding="utf-8"
        )

    content = read_lines(structure_txt)
    lines: list[str] = []
    lines.append("# Project Structure")
    lines.append("")
    lines.append(f"_Auto-generated by refresh_project_maps.py at {ts}_")
    lines.append("")
    lines.append("```")
    lines.extend(content)
    lines.append("```")
    lines.append("")
    write_md(AGENTS_DIR / "project_structure.md", "\n".join(lines))


def build_templates_map() -> None:
    ts = datetime.now().isoformat(timespec="seconds")
    all_templates_txt = AGENTS_DIR / "all_templates.txt"
    maybe_unused_txt = AGENTS_DIR / "maybe_unused_templates_clean.txt"

    if not all_templates_txt.is_file():
        all_templates: list[str] = []
        if TEMPLATES_DIR.is_dir():
            for p in TEMPLATES_DIR.rglob("*.html"):
                all_templates.append(str(p))
        all_templates_txt.write_text(
            "\n".join(sorted(all_templates)), encoding="utf-8"
        )

    all_templates = [l for l in read_lines(all_templates_txt) if l.strip()]
    unused_set = set(read_lines(maybe_unused_txt)) if maybe_unused_txt.is_file() else set()

    lines: list[str] = []
    lines.append("# Templates Map")
    lines.append("")
    lines.append(f"_Auto-generated by refresh_project_maps.py at {ts}_")
    lines.append("")
    lines.append(
        "Status legend: **active** = referenced somewhere; "
        "**unused-candidate** = not detected in code/other templates."
    )
    lines.append("")
    for full in sorted(all_templates):
        rel = str(Path(full).relative_to(PROJECT_ROOT))
        status = "unused-candidate" if full in unused_set else "active"
        lines.append(f"- `{rel}` — **{status}**")
    lines.append("")
    write_md(AGENTS_DIR / "templates_map.md", "\n".join(lines))


def build_static_map() -> None:
    ts = datetime.now().isoformat(timespec="seconds")
    all_static_txt = AGENTS_DIR / "all_static_files.txt"

    if not all_static_txt.is_file():
        static_files: list[str] = []
        if STATIC_DIR.is_dir():
            for p in STATIC_DIR.rglob("*"):
                if p.is_file():
                    static_files.append(str(p))
        all_static_txt.write_text(
            "\n".join(sorted(static_files)), encoding="utf-8"
        )

    all_static = [l for l in read_lines(all_static_txt) if l.strip()]

    lines: list[str] = []
    lines.append("# Static Files Map")
    lines.append("")
    lines.append(f"_Auto-generated by refresh_project_maps.py at {ts}_")
    lines.append("")
    for full in sorted(all_static):
        rel = str(Path(full).relative_to(PROJECT_ROOT))
        lines.append(f"- `{rel}`")
    lines.append("")
    write_md(AGENTS_DIR / "static_map.md", "\n".join(lines))


def build_migrations_status() -> None:
    ts = datetime.now().isoformat(timespec="seconds")
    all_migrations_txt = AGENTS_DIR / "all_migrations.txt"
    migration_status_txt = AGENTS_DIR / "migration_status.txt"

    lines: list[str] = []
    lines.append("# Migrations Status")
    lines.append("")
    lines.append(f"_Auto-generated by refresh_project_maps.py at {ts}_")
    lines.append("")

    if all_migrations_txt.is_file():
        lines.append("## Migration Files")
        lines.append("")
        for full in sorted(read_lines(all_migrations_txt)):
            if not full.strip():
                continue
            rel = str(Path(full).relative_to(PROJECT_ROOT))
            lines.append(f"- `{rel}`")
        lines.append("")

    if migration_status_txt.is_file():
        lines.append("## Django showmigrations Output")
        lines.append("")
        lines.append("```")
        lines.extend(read_lines(migration_status_txt))
        lines.append("```")
        lines.append("")
    else:
        lines.append(
            "*(migration_status.txt not found – run "
            "`python manage.py showmigrations > .continue/agents/migration_status.txt` "
            "and re-run this script.)*"
        )
        lines.append("")

    write_md(AGENTS_DIR / "migrations_status.md", "\n".join(lines))


def build_models_map() -> None:
    ts = datetime.now().isoformat(timespec="seconds")
    extracted_models_txt = AGENTS_DIR / "extracted_models.txt"
    models_py = RESOURCES_DIR / "models.py"

    models: list[str] = []
    if extracted_models_txt.is_file():
        for line in read_lines(extracted_models_txt):
            if line.strip():
                models.append(line.strip())
    elif models_py.is_file():
        text = models_py.read_text(encoding="utf-8", errors="ignore")
        pattern = r"^class\s+([A-Za-z0-9_]+)\s*\(models\.Model\)"
        for m in re.finditer(pattern, text, flags=re.MULTILINE):
            models.append(f"class {m.group(1)}(models.Model):")

    lines: list[str] = []
    lines.append("# Models Map")
    lines.append("")
    lines.append(f"_Auto-generated by refresh_project_maps.py at {ts}_")
    lines.append("")
    if not models:
        lines.append("No models found or `extracted_models.txt` missing.")
    else:
        lines.append("## resources.models")
        lines.append("")
        for mline in models:
            lines.append(f"- `{mline}`")
    lines.append("")
    write_md(AGENTS_DIR / "models_map.md", "\n".join(lines))


def main() -> None:
    build_project_overview()
    build_project_structure()
    build_templates_map()
    build_static_map()
    build_migrations_status()
    build_models_map()
    print("Project maps refreshed under .continue\\agents")


if __name__ == "__main__":
    main()
