# Generated by Django 5.2.1 on 2025-10-16 11:07

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OERSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., OAPEN, DOAB, OER Commons",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this OER source"
                    ),
                ),
                ("website", models.URLField(blank=True, help_text="Main website URL")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("rest_api", "REST API"),
                            ("oai_pmh", "OAI-PMH"),
                            ("rss_feed", "RSS Feed"),
                            ("csv_url", "CSV URL"),
                            ("custom", "Custom"),
                        ],
                        default="rest_api",
                        max_length=50,
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(help_text="Main API endpoint URL", max_length=500),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API key if required (stored securely)",
                        max_length=500,
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        choices=[("GET", "GET"), ("POST", "POST")],
                        default="GET",
                        max_length=10,
                    ),
                ),
                (
                    "request_headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"Authorization": "Bearer token", "Accept": "application/json"}',
                    ),
                ),
                (
                    "request_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"format": "json", "per_page": 100}',
                    ),
                ),
                (
                    "field_mappings",
                    models.JSONField(
                        default=dict,
                        help_text='Map API fields to OER model fields: {"title": "data.attributes.title", "url": "data.links.self"}',
                    ),
                ),
                ("supports_pagination", models.BooleanField(default=True)),
                (
                    "pagination_type",
                    models.CharField(
                        choices=[
                            ("page_number", "Page Number"),
                            ("offset_limit", "Offset/Limit"),
                            ("cursor", "Cursor"),
                            ("link_header", "Link Header"),
                            ("none", "No Pagination"),
                        ],
                        default="page_number",
                        max_length=50,
                    ),
                ),
                (
                    "pagination_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"page_param": "page", "per_page_param": "per_page", "max_per_page": 100}',
                    ),
                ),
                (
                    "results_path",
                    models.CharField(
                        default="results",
                        help_text="JSON path to results array: 'data', 'results', 'items', etc.",
                        max_length=200,
                    ),
                ),
                (
                    "total_count_path",
                    models.CharField(
                        blank=True,
                        help_text="JSON path to total count: 'meta.total', 'count', etc.",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable harvesting from this source",
                    ),
                ),
                (
                    "harvest_schedule",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Only"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=50,
                    ),
                ),
                (
                    "max_resources_per_harvest",
                    models.IntegerField(
                        default=1000,
                        help_text="Maximum resources to fetch per harvest (0 = unlimited)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("testing", "Testing"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_harvest_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_harvest_count",
                    models.IntegerField(
                        default=0, help_text="Resources harvested in last run"
                    ),
                ),
                (
                    "total_harvested",
                    models.IntegerField(
                        default=0,
                        help_text="Total resources harvested from this source",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, help_text="Last error message if any"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "OER Source",
                "verbose_name_plural": "OER Sources",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="OERResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(max_length=500)),
                ("license", models.CharField(blank=True, max_length=100)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("level", models.CharField(blank=True, max_length=100)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("language", models.CharField(blank=True, default="en", max_length=50)),
                ("resource_type", models.CharField(blank=True, max_length=100)),
                ("format", models.CharField(blank=True, max_length=100)),
                (
                    "content_embedding",
                    pgvector.django.vector.VectorField(dimensions=384, null=True),
                ),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("ai_generated_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_verified", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="resources.oersource",
                    ),
                ),
            ],
            options={
                "verbose_name": "OER Resource",
                "verbose_name_plural": "OER Resources",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["title", "source"], name="resources_o_title_eb3df7_idx"
                    ),
                    models.Index(
                        fields=["resource_type", "language"],
                        name="resources_o_resourc_cb499d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HarvestJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partially Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("resources_found", models.IntegerField(default=0)),
                ("resources_created", models.IntegerField(default=0)),
                ("resources_updated", models.IntegerField(default=0)),
                ("resources_skipped", models.IntegerField(default=0)),
                ("resources_failed", models.IntegerField(default=0)),
                ("pages_processed", models.IntegerField(default=0)),
                ("api_calls_made", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                (
                    "log_messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of log messages during harvest",
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        blank=True,
                        help_text="User or system that triggered harvest",
                        max_length=100,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harvest_jobs",
                        to="resources.oersource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harvest Job",
                "verbose_name_plural": "Harvest Jobs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "-started_at"],
                        name="resources_h_source__6cc963_idx",
                    ),
                    models.Index(
                        fields=["status", "-started_at"],
                        name="resources_h_status_07b095_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OERSourceFieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_field_path",
                    models.CharField(
                        help_text="JSON path in API response: 'data.attributes.title'",
                        max_length=300,
                    ),
                ),
                (
                    "target_field",
                    models.CharField(
                        help_text="OER model field name: 'title', 'description', etc.",
                        max_length=100,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Skip resource if this field is missing",
                    ),
                ),
                (
                    "default_value",
                    models.CharField(
                        blank=True,
                        help_text="Default value if field is missing",
                        max_length=500,
                    ),
                ),
                (
                    "transformation_rule",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Copy"),
                            ("lowercase", "Convert to Lowercase"),
                            ("uppercase", "Convert to Uppercase"),
                            ("strip_html", "Strip HTML Tags"),
                            ("join_list", "Join List with Comma"),
                            ("first_item", "Take First Item from List"),
                            ("custom", "Custom Transformation"),
                        ],
                        default="direct",
                        max_length=50,
                    ),
                ),
                (
                    "custom_transformation",
                    models.TextField(
                        blank=True, help_text="Python code for custom transformation"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Processing order (higher = first)"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailed_mappings",
                        to="resources.oersource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Mapping",
                "verbose_name_plural": "Field Mappings",
                "ordering": ["-priority", "target_field"],
                "unique_together": {("source", "target_field")},
            },
        ),
    ]
