# Generated by Django 5.2.1 on 2025-10-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oersource",
            name="api_endpoint",
            field=models.CharField(
                help_text="Main API endpoint URL or path (e.g., /rest/search)",
                max_length=500,
            ),
        ),
    ]
