# Generated by Django 5.2.1 on 2025-11-06 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_oersource_api_endpoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oersourcefieldmapping',
            options={'ordering': ['-is_required', 'target_model_fields'], 'verbose_name': 'Field Mapping', 'verbose_name_plural': 'Field Mappings'},
        ),
        migrations.RemoveIndex(
            model_name='harvestjob',
            name='resources_h_source__6cc963_idx',
        ),
        migrations.RemoveIndex(
            model_name='harvestjob',
            name='resources_h_status_07b095_idx',
        ),
        migrations.AlterUniqueTogether(
            name='oersourcefieldmapping',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='oersource',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='oersource',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='oersource',
            name='last_harvest_count',
        ),
        migrations.RemoveField(
            model_name='oersource',
            name='request_method',
        ),
        migrations.RemoveField(
            model_name='oersource',
            name='total_count_path',
        ),
        migrations.RemoveField(
            model_name='oersource',
            name='website',
        ),
        migrations.AddField(
            model_name='oersource',
            name='api_url',
            field=models.URLField(blank=True, help_text='Base URL for the API (e.g., https://example.com/api)', null=True),
        ),
        migrations.AddField(
            model_name='oersource',
            name='csv_url',
            field=models.URLField(blank=True, help_text='CSV file URL for CSV harvesting', null=True),
        ),
        migrations.AddField(
            model_name='oersource',
            name='oaipmh_set_spec',
            field=models.CharField(blank=True, help_text='Set specification for the OAI-PMH harvest', max_length=200),
        ),
        migrations.AddField(
            model_name='oersource',
            name='oaipmh_url',
            field=models.URLField(blank=True, help_text='OAI-PMH URL (e.g., https://example.com/oai)', null=True),
        ),
        migrations.AddField(
            model_name='oersourcefieldmapping',
            name='target_model_fields',
            field=models.JSONField(default=dict, help_text='{"OERResource": {"title": "data.title", "description": "data.description"}}'),
        ),
        migrations.AlterField(
            model_name='harvestjob',
            name='log_messages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='harvestjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='harvestjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='harvestjob',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oersource',
            name='api_endpoint',
            field=models.URLField(blank=True, help_text='API endpoint URL (e.g., https://example.com/api/v1/resources)', null=True),
        ),
        migrations.AlterField(
            model_name='oersource',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key if required (stored securely)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='oersource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='oersource',
            name='field_mappings',
        ),
        migrations.AlterField(
            model_name='oersource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='oersource',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='oersource',
            name='pagination_config',
            field=models.JSONField(blank=True, default=dict, help_text='{"page_param": "page", "per_page_param": "per_page"}'),
        ),
        migrations.AlterField(
            model_name='oersource',
            name='results_path',
            field=models.CharField(default='results', help_text="JSON path to results array (e.g., 'data.results')", max_length=200),
        ),
        migrations.AlterField(
            model_name='oersource',
            name='source_type',
            field=models.CharField(choices=[('API', 'API Harvester'), ('OAIPMH', 'OAI-PMH Harvester')], default='API', help_text='Select the type of harvester to use for this source', max_length=50),
        ),
        migrations.AlterField(
            model_name='oersource',
            name='total_harvested',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='oersourcefieldmapping',
            name='custom_transformation',
            field=models.TextField(blank=True, help_text='Python code for custom transformation (e.g., lambda x: x.upper())'),
        ),
        migrations.AlterField(
            model_name='oersourcefieldmapping',
            name='default_value',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='oersourcefieldmapping',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oersourcefieldmapping',
            name='source_field_path',
            field=models.CharField(help_text="JSON path in API response (e.g., 'data.attributes.title')", max_length=300),
        ),
        migrations.RemoveField(
            model_name='oersourcefieldmapping',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='oersourcefieldmapping',
            name='source',
        ),
        migrations.RemoveField(
            model_name='oersourcefieldmapping',
            name='target_field',
        ),
        migrations.AddField(
            model_name='oersource',
            name='field_mappings',
            field=models.ManyToManyField(blank=True, help_text='Map API fields to OER model fields', related_name='sources', to='resources.oersourcefieldmapping'),
        ),
    ]
