# Generated by Django 5.2.1 on 2025-11-10 09:18

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_alter_oersourcefieldmapping_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oersource",
            name="api_url",
        ),
        migrations.RemoveField(
            model_name="oersource",
            name="pagination_config",
        ),
        migrations.RemoveField(
            model_name="oersource",
            name="pagination_type",
        ),
        migrations.RemoveField(
            model_name="oersource",
            name="results_path",
        ),
        migrations.RemoveField(
            model_name="oersource",
            name="supports_pagination",
        ),
        migrations.AlterField(
            model_name="harvestjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("partial", "Partial"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="oerresource",
            name="content_embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=384, null=True
            ),
        ),
        migrations.AlterField(
            model_name="oersource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("API", "API Harvester"),
                    ("OAIPMH", "OAI-PMH Harvester"),
                    ("CSV", "CSV Harvester"),
                ],
                default="API",
                help_text="Select the type of harvester to use for this source",
                max_length=20,
            ),
        ),
    ]
