# Generated by Django 5.2.1 on 2025-11-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_oersource_api_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oersource',
            name='marcxml_url',
            field=models.URLField(blank=True, help_text='MARCXML file URL for MARCXML harvesting (or dump URL)', null=True),
        ),
        migrations.AlterField(
            model_name='oersource',
            name='source_type',
            field=models.CharField(choices=[('API', 'API Harvester'), ('OAIPMH', 'OAI-PMH Harvester'), ('CSV', 'CSV Harvester'), ('MARCXML', 'MARCXML Harvester')], default='API', help_text='Select the type of harvester to use for this source', max_length=20),
        ),
    ]
