# Generated by Django 5.2.1 on 2025-11-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0006_add_talispushjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="oerresource",
            name="overall_quality_score",
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
