# Generated by Django 5.2.1 on 2025-12-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0007_oerresource_overall_quality_score"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="oersource",
            options={
                "ordering": ["display_name", "name"],
                "verbose_name": "OER Source",
                "verbose_name_plural": "OER Sources",
            },
        ),
        migrations.AddField(
            model_name="oerresource",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="English translation of description (auto-generated during harvest)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="oerresource",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="English translation of title (auto-generated during harvest)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="oersource",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="User-friendly display name (e.g., 'OAPEN Open Access Books' instead of 'OAPEN MARCXML dump')",
                max_length=200,
            ),
        ),
    ]
