# Generated by Django 5.2.1 on 2025-12-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0009_populate_source_display_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="oerresource",
            name="doi",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="DOI string as provided (not URL).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="oerresource",
            name="isbn",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Normalised ISBN-10 or ISBN-13 without punctuation.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="oerresource",
            name="issn",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Normalised ISSN without punctuation.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="oerresource",
            name="oclc_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="OCLC control number (normalised digits only where possible).",
                max_length=32,
            ),
        ),
    ]
