# Generated by Django 5.2.1 on 2025-12-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resources",
            "0010_oerresource_doi_oerresource_isbn_oerresource_issn_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="oerresource",
            name="normalised_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("book", "Book / Monograph"),
                    ("chapter", "Book Chapter"),
                    ("article", "Article"),
                    ("video", "Video"),
                    ("course", "Course / Module"),
                    ("other", "Other"),
                ],
                db_index=True,
                help_text="Normalised internal type derived from source metadata.",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="oerresource",
            index=models.Index(
                fields=["normalised_type", "language"],
                name="resources_o_normali_3f33f8_idx",
            ),
        ),
    ]
