# Generated by Django 5.2.1 on 2025-12-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_oerresource_normalised_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oerresource',
            name='ai_subjects',
            field=models.JSONField(blank=True, default=list, help_text='AI-suggested subject labels.'),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='primary_subject',
            field=models.CharField(blank=True, help_text='Preferred subject (source or AI-enriched).', max_length=100),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='subjects_raw',
            field=models.JSONField(blank=True, default=list, help_text='All subject strings from source metadata.'),
        ),
    ]
