# Generated by Django 5.2.1 on 2025-12-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_oerresource_ai_subjects_oerresource_primary_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oerresource',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash of downloaded content to avoid re-processing', max_length=64),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='content_source_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('html', 'HTML'), ('other', 'Other')], help_text='Detected content type for extracted_text', max_length=20),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='extracted_at',
            field=models.DateTimeField(blank=True, help_text='When content was extracted', null=True),
        ),
        migrations.AddField(
            model_name='oerresource',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Normalized extracted text from linked PDF or webpage', null=True),
        ),
    ]
